class Exception {
  var v:int;
  method Exception(v:int) {
    print("Exception ", v, " thrown!\n");
    this.v = v;
  }
  method get():int {
    return v;
  }
}

class main {

  method foo() {
    try {
      throw new Exception(5);
      print(17);                           // should not be printed
    } catch(e : class Exception) {
      throw new Exception(e.get() + 2);    // throws 7
    }
    throw new Exception(-1);               // should not be reached
  }

  method main() {
    try
      foo();
    catch(e : class Exception)
      print(e.get(),"\n");  // should print 7
  }

}

// 7
