finally after uncaught exception
Thread terminated with exception: Exception2: ex2
